AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
